variable "resource_group_name" {}
variable "location" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "nsg_name" {}
variable "kubernetes_cluster_name" {}
variable "node_count" {}
variable "address_space" {}
variable "address_prefixes" {}
variable "node_vm_size" {}
variable "network_profile_plugin" {}
variable "network_profile_service_cidr" {}
variable "network_profile_dns_service_ip" {}
variable "azure_subscription_id" {}
variable "azure_client_id" {}
variable "azure_client_secret" {}
variable "azure_tenant_id" {}
