apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIuYWtvc3RhZ2UuaXIiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2WVd0dmNtRjVZVzQ9IgoJCX0KCX0KfQo=
type: kubernetes.io/dockerconfigjson